# Generated by Django 4.0 on 2022-01-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
